// KANBANBOARD

export const FETCH_KANBANBOARD_COLUMNS_SUCCESS = 'FETCH_KANBANBOARD_COLUMNS_SUCCESS'
export const FETCH_KANBANBOARD_TASKS_SUCCESS = 'FETCH_KANBANBOARD_TASKS_SUCCESS'
export const FETCH_KANBANBOARD_ORDER_SUCCESS = 'FETCH_KANBANBOARD_ORDER_SUCCESS'

export const UPDATE_KANBANBOARD_STATE = 'UPDATE_KANBANBOARD_STATE' //Internally use to update front-end.

export const CREATE_KANBANBOARD_TASK = 'CREATE_KANBANBOARD_TASK'
export const UPDATE_KANBANBOARD_TASK = 'UPDATE_KANBANBOARD_TASK'

export const UPDATE_KANBANBOARD_COLUMN_ORDER_SUCCESS = 'UPDATE_KANBANBOARD_COLUMN_ORDER_SUCCESS' // Update column order on the board.
// export const UPDATE_KANBANBOARD_TASK_ORDER_SUCCESS = 'UPDATE_KANBANBOARD_TASK_ORDER_SUCCESS' // Update column order on the board.

export const LOADING_KANBANBOARD_TASKS = 'LOADING_KANBANBOARD_TASKS'
export const LOADING_KANBANBOARD_COLUMNS = 'LOADING_KANBANBOARD_COLUMNS'
export const LOADING_KANBANBOARD_COLUMNORDER = 'LOADING_KANBANBOARD_COLUMNORDER'


// TASKS_LIST TABLE

export const FETCH_TASKS_LIST_SUCCESS = 'FETCH_TASKS_LIST_SUCCESS'
export const UPDATE_TASK_COLUMN_SUCCESS = 'UPDATE_TASK_COLUMN_SUCCESS'
export const UPDATE_TASK_COLUMN_ORDER_SUCCESS = 'UPDATE_TASK_COLUMN_ORDER_SUCCESS'
export const REMOVE_TASKS_LIST_SUCCESS = 'REMOVE_TASKS_LIST_SUCCESS' //Removes specific task by id

export const LOADING_TASKLIST_TASKS = 'LOADING_TASK_TASKS'

// PROJECTS_LIST TABLE

export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS'


// RECORD

export const FETCH_RECORD_LIST_SUCCESS = 'FETCH_RECORD_LIST_SUCCESS'
export const CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS'

//
// INTERNAL STATE USE
// STATS
//

// POMODORO

export const FETCH_POMODORO_SUCCESS = 'FETCH_POMODORO_SUCCESS'


// React native

export const UPDATE_POMODOROPICKERFORM_PICKERITEM = 'UPDATE_POMODOROPICKERFORM_PICKERITEM'

// Timer

export const STOP_TIMER = 'STOP_TIMER'
export const START_TIMER = 'START_TIMER'
export const TICK = 'TICK'
export const FINISHED_TIMER = 'FINISHED_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
